
spring:
 profiles:
   active: dev
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/dbgirl
   username: root
   password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true

   spring:
     devtools:
       restart:
         enabled: true

 thymeleaf:
   servlet:
     content-type: text/html
   encoding: utf-8
   mode: HTML5
   suffix: .html
   prefix: classpath:/templates/
   cache: false

 resources:
   chain:
     strategy:
       content:
         enabled: true
         paths:
 redis:
   database: 0
   host: 192.168.10.103
   port: 6379
   password:
   jedis:
     pool:
       max-active: 5000
       max-wait: 3000
       max-idle: 30
       min-idle: 5
   timeout: 10000
   cluster:
     nodes: 192.168.1.171:7001,192.168.1.171:7002,192.168.1.171:7003,192.168.1.171:7004,192.168.1.171:7005,192.168.1.171:7006

     # ES
 data:
   elasticsearch:
     cluster-nodes: 192.168.10.103:9300
     cluster-name:  elasticsearch
     repositories:
       enabled: true


server.tomcat.access_log_enabled: true
server.tomcat.basedir: target/tomcat


